Update turkish.lang
wiidev/usbloadergx pull request #44
Opened 2024-09-26 20:30 UTC by Reqrefusion

All Turkish translations have been completed. I'm not sure about some of them.

2025-04-12 08:34 UTC, Dumpflam approved these changes
Sonunda be! sen yapmasaydın ben yapacaktım ama chatgpt kullanacaktım XD türk wiicileri az bulunuyor...

2025-04-12 08:49 UTC, Reqrefusion commented
> Sonunda be! sen yapmasaydın ben yapacaktım ama chatgpt kullanacaktım XD türk wiicileri az bulunuyor...

Türk wiicilere selam olsun. Ama çevirirken bazı şeyleri çok uzun yapmışım. Wii de açıp kontrol ederek bakmak lazım.

2025-04-12 09:01 UTC, Dumpflam requested changes
ilk satırlarda "problem" yerine "sorun" kullanmak lazım. problem türkçede var ama türkçe değil.

2025-04-12 09:02 UTC, Dumpflam commented
> > Sonunda be! sen yapmasaydın ben yapacaktım ama chatgpt kullanacaktım XD türk wiicileri az bulunuyor...
> 
> Türk wiicilere selam olsun. Ama çevirirken bazı şeyleri çok uzun yapmışım. Wii de açıp kontrol ederek bakmak lazım.

Ben kontrol edebilirim şimdi, olur mu?

2025-04-12 09:14 UTC, Reqrefusion commented
> ilk satırlarda "problem" yerine "sorun" kullanmak lazım. problem türkçede var ama türkçe değil.

Bu öz türkçelerşitme olayına karşıyım. Ama sorun daha kısa bir kelime olduğu için doğru bir değişiklik olacaktır. İncelemeleri buraya değilde belgenin üstüne yapsanız benim değişiklik yapmam daha kolay olur.

2025-04-13 05:50 UTC, Dumpflam commented
Merhaba, senin dosyanı bir uçtan diğer uca kontrol ettim ve bulduğum hataları veya daha iyi olabilecekleri düzelttim. öz türkçeleştirme YAPMADIM. hem bi sorum var: Öykünülme ne? Emülasyon yerine öyle yazmışsın. Dosyada bazı yerlerde çift (") vardı, bazı yerlerde de üsttekinin çevirisini alttakine yazmışsın yanlışlıkla üstteki boş kalmış alttaki de yanlış olmuş, bir yerde "versiyon" yerine "vesiyon" yazmışsın. neyse boşver çok düzenleme yaptım yani. Acaba (pls pls pls) kendi adımı dosyaya eklesem sıkıntı olurmu? dün buraya yazdığımdan beri durmaksızın çalıştım. (Dosya: https://drive.google.com/file/d/1Gk52Kev9JzsULxcFKy9fYfGK0oROfB72/view?usp=sharing)

2025-04-13 12:19 UTC, Reqrefusion commented
> Merhaba, senin dosyanı bir uçtan diğer uca kontrol ettim ve bulduğum hataları veya daha iyi olabilecekleri düzelttim. öz türkçeleştirme YAPMADIM. hem bi sorum var: Öykünülme ne? Emülasyon yerine öyle yazmışsın. Dosyada bazı yerlerde çift (") vardı, bazı yerlerde de üsttekinin çevirisini alttakine yazmışsın yanlışlıkla üstteki boş kalmış alttaki de yanlış olmuş, bir yerde "versiyon" yerine "vesiyon" yazmışsın. neyse boşver çok düzenleme yaptım yani. Acaba (pls pls pls) kendi adımı dosyaya eklesem sıkıntı olurmu? dün buraya yazdığımdan beri durmaksızın çalıştım. (Dosya: https://drive.google.com/file/d/1Gk52Kev9JzsULxcFKy9fYfGK0oROfB72/view?usp=sharing)

Tabi neden olmasın zaten bunun amacı o değil mi. Ama sizde kısaltma yapmamışsınız bu çeviriyi konsolda denediyseniz. Bunun nedenini fark edeceksiniz.

Hemde bunu zaten pek fazla kişinin kıllanacağınıda zannetmiyorum. Ayrıca burası ölü bir yer olduğu için bu PR da kabul edilmeyecek.

2025-04-13 12:23 UTC, Dumpflam commented
> > Merhaba, senin dosyanı bir uçtan diğer uca kontrol ettim ve bulduğum hataları veya daha iyi olabilecekleri düzelttim. öz türkçeleştirme YAPMADIM. hem bi sorum var: Öykünülme ne? Emülasyon yerine öyle yazmışsın. Dosyada bazı yerlerde çift (") vardı, bazı yerlerde de üsttekinin çevirisini alttakine yazmışsın yanlışlıkla üstteki boş kalmış alttaki de yanlış olmuş, bir yerde "versiyon" yerine "vesiyon" yazmışsın. neyse boşver çok düzenleme yaptım yani. Acaba (pls pls pls) kendi adımı dosyaya eklesem sıkıntı olurmu? dün buraya yazdığımdan beri durmaksızın çalıştım. (Dosya: https://drive.google.com/file/d/1Gk52Kev9JzsULxcFKy9fYfGK0oROfB72/view?usp=sharing)
> 
> Tabi neden olmasın zaten bunun amacı o değil mi. Ama sizde kısaltma yapmamışsınız bu çeviriyi konsolda denediyseniz. Bunun nedenini fark edeceksiniz.
> 
> Hemde bunu zaten pek fazla kişinin kıllanacağınıda zannetmiyorum. Ayrıca burası ölü bir yer olduğu için bu PR da kabul edilmeyecek.

Ne olacak, bunu gören türkler kullanır. konsolda daha denemedim, bugün deneyeceğim. kısaltmalara bakarım boş vaktimde.

2025-04-13 12:26 UTC, Dumpflam commented
Adımı eklediğim yeni dosya: https://drive.google.com/file/d/1tyBdF3waMHVsd3337yvHB41nChn0mQlw/view?usp=sharing

2025-06-19 18:26 UTC, wiidev commented
Please check the new translation files in a few days.

2025-06-19 18:26 UTC, closed without merging